language: java
jdk:
- oraclejdk8
services:
- mysql
- docker
dist: trusty
sudo: required
addons:
apt:
packages:
- mysql-server-5.7
- mysql-client-core-5.7
- mysql-client-5.7
before_script:
- mysql -u root -e 'CREATE DATABASE empleado;'
- mysql -u root -e "GRANT ALL ON empleado.* TO 'root'@'localhost';"
before_install:
- chmod +x mvnw
- ./mvnw.cmd clean install 
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin