language: java
jdk:
  - oraclejdk8
services:
  - mysql
  - docker
dist: trusty
sudo: required
packages:
  - mysql-server-5.7
  - mysql-client-core-5.7
  - mysql-client-5.7
before_script:
  - mysql -u root -e 'CREATE DATABASE empleado;'
  - mysql -u root -e "GRANT ALL ON empleado.* TO 'root'@'localhost';"
before_install:
  - chmod +x mvnw ./mvnw.cmd
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
script:
  - docker build -t dmrmejiar/empleado-sa .
  - docker pull mysql:5.7
  - docker tag dmrmejiar/empleado-sa registry.heroku.com/$HEROKU_APP_NAME/web
  - docker tag mysql dmrmejiar/mysql-standalone
  - docker tag dmrmejiar/mysql-standalone registry.heroku.com/$HEROKU_DB_NAME/web
deploy:
  provider: script
  script:
    docker push dmrmejiar/mysql-standalone;
    docker push registry.heroku.com/$HEROKU_DB_NAME/web;
    docker push dmrmejiar/empleado-sa;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_DB_NAME;
    heroku container:release web --app $HEROKU_APP_NAME
  branch: master