version: '3.3'
services:
  db:
    image: dmrmejiar/mysql-standalone
    container_name: dmrmejiar/mysql-standalone
    environment:
      MYSQL_ROOT_PASSWORD: "sa"
      MYSQL_DATABASE: "empleado"
      MYSQL_PASSWORD: "sa"

  app:
    image: dmrmejiar/empleado-sa
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dmrmejiar/empleado-sa
    working_dir: /usr/src/
    ports:
      - "8089:8089" 
    depends_on:
      - db